// let driverLincence = (passTest) => {
//     if(true) {
//         let result = 1;
//     }
//  console.log(result);
 
// }

// driverLincence(true);
// console.log(driverLincence);




     // ES6

let x = 3;
// console.log(x);

function func(randomize) {
    if (randomize) {
        let x = Math.random();
        return x;
    }
    return x;

    console.log(x);
    
}
let result =func(false); // 3
let result2 =func(true); // 3

console.log(result);
console.log(result2);


//  IIFE (Immediately-Invoked Function Expression)  ES6
// if you wanted to restrict the scope of a variable tmp to a block

{  // open block
    let tmp = 3;

}  // close block

// ReferenceError  console.log(tmp); 



const [, year, month, day] =
    /^(\d\d\d\d)-(\d\d)-(\d\d)$/
    .exec('2999-12-31');

    console.log(year);
    
    console.log(month);
    
    console.log(day);
    

    # Logs
    logs
    *.log
    npm-debug.log*
    yarn-debug.log*
    yarn-error.log*
    
    # Runtime data
    pids
    *.pid
    *.seed
    *.pid.lock
    
    # Directory for instrumented libs generated by jscoverage/JSCover
    lib-cov
    
    # Coverage directory used by tools like istanbul
    coverage
    
    # nyc test coverage
    .nyc_output
    
    # Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)
    .grunt
    
    # Bower dependency directory (https://bower.io/)
    bower_components
    
    # node-waf configuration
    .lock-wscript
    
    # Compiled binary addons (https://nodejs.org/api/addons.html)
    build/Release
    
    # Dependency directories
    node_modules/
    jspm_packages/
    
    # TypeScript v1 declaration files
    typings/
    
    # Optional npm cache directory
    .npm
    
    # Optional eslint cache
    .eslintcache
    
    # Optional REPL history
    .node_repl_history
    
    # Output of 'npm pack'
    *.tgz
    
    # Yarn Integrity file
    .yarn-integrity
    
    # dotenv environment variables file
    .env
    
    # next.js build output
    .next